### ISSUE TITLE
Error while switching rapidly on different channels

### ISSUE THREAD

**Issue by zThundy** [KuryGabriele/echo-project#3]
![image](https://github.com/KuryGabriele/echo-project/assets/25564154/87354e3c-5f03-4e18-bc87-ef6d86f127f5)

To be checked

**Comment by KuryGabriele** [comment]
Personal note, line 269 remove stream from inputstreams after closing it.

**Comment by KuryGabriele** [comment]
There is another issue with joining a bunch of channels fast. When subscribing to a stream, there might be an ice gathering state again that takes time. This makes it so that on the server side the unsubs arrive for subs that are being done. Which makes the audio stream not work.

TLDR we need to limit the joins. I was thinking of creating an event like doneJoining that enables switching rooms only when true.
